#!/usr/bin/env bash
# Install and configure Nginx to use port 8080 instead of port 808
apt-get install nginx -y
sed -i 's/80/8080/g' /etc/nginx/nginx.conf
$(service nginx stop) $(service nginx start)
